"""End-to-end run on synthetic data:

    python -m sde.demo

The locus is generated by this file, so finding the planted array proves only
that the machinery works. What the demo is actually for is showing the shape of
the record: which tool ran, why it was requested, what it returned, what the
adversary said, and what stayed unresolved.

The investigator here is scripted, not a model. It follows the path the ART
account describes — look at the neighbourhood, notice something odd, go back to
the raw DNA, find the repeats — so the control flow is exercised without
pretending a stand-in reasons like a model would.
"""

from __future__ import annotations

import json
import random
from pathlib import Path

from sde.adversary import AdversarialReview
from sde.loop import InvestigationLoop, ScriptedInvestigator
from sde.report import DiscoveryReport
from sde.state import CandidateState
from sde.tools import registry

UNIT = "CATGTGTATCGCATGTTACGTACGT"
KNOWN_ARCHITECTURES = [["RT", "capsid"], ["RT", "integrase", "capsid"]]


def synthesise(seed: int = 0) -> str:
    """A locus with an RT-adjacent tandem array at ~140 bp spacing."""
    rng = random.Random(seed)
    dna = ["".join(rng.choice("ACGT") for _ in range(400))]
    for _ in range(9):
        dna.append(UNIT + "".join(rng.choice("ACGT") for _ in range(140 - len(UNIT))))
    dna.append("".join(rng.choice("ACGT") for _ in range(400)))
    return "".join(dna)


def script(sequence: str) -> list[dict]:
    """The investigation path, as a sequence of agent steps."""
    return [
        {
            "observation": "Nothing computed yet; start with the cheapest evidence.",
            "request": {
                "tool": "sequence_stats",
                "reason": "establish composition before anything expensive",
                "inputs": {"sequence": sequence},
            },
        },
        {
            "observation": "Composition is unremarkable. Look at the gene neighbourhood.",
            "request": {
                "tool": "neighbourhood_novelty",
                "reason": "an RT beside an unnamed partner would be the interesting case",
                "inputs": {
                    "genes": [
                        {"family": "RT"},
                        {"family": "orfX"},
                        {"family": "orfY"},
                    ],
                    "anchor_family": "RT",
                    "known_architectures": KNOWN_ARCHITECTURES,
                    "known_families": ["RT", "capsid", "integrase"],
                },
            },
        },
        {
            "observation": (
                "The architecture matches no described system. Back to the raw DNA."
            ),
            "hypotheses": [
                {
                    "statement": "RT sits in an uncharacterised system with an unnamed partner",
                    "discriminating_evidence": (
                        "an Rfam/Infernal scan of the intervening sequence"
                    ),
                    "confidence": 0.5,
                }
            ],
            "request": {
                "tool": "repeat_scan",
                "reason": "check whether the intervening DNA is structured rather than random",
                "inputs": {"sequence": sequence},
            },
        },
        {
            "observation": (
                "Nine copies at a near-constant period. Not what I was looking for."
            ),
            "hypotheses": [
                {
                    "statement": "The locus contains a tandem repeat array with ~140 bp spacing",
                    "discriminating_evidence": (
                        "the consensus unit, and whether it recurs in other genomes"
                    ),
                    "confidence": 0.8,
                }
            ],
            "request": {
                "tool": "repeat_detail",
                "reason": "recover the consensus unit to compare against known arrays",
                "inputs": {"sequence": sequence},
            },
        },
        {
            "observation": (
                "Consensus recovered. Confirming novelty needs Infernal, not installed."
            ),
            "request": {
                "tool": "infernal_scan",
                "reason": "rule out a described structured RNA family",
                "inputs": {"sequence": sequence[:200]},
            },
        },
        {
            "observation": (
                "Infernal is unavailable, so novelty cannot be established here."
            ),
            "stop": True,
            "stop_reason": (
                "the decisive tool is not installed; cheaper tools cannot settle it"
            ),
        },
    ]


class CautiousAdversary:
    """Stands in for a skeptical model, without pretending to be one.

    It answers from the computed evidence: a perfectly regular period is
    exactly what a collapsed assembly looks like, so it presses that point and
    declines to rule on questions the evidence cannot answer.
    """

    def complete(self, system: str, prompt: str) -> str:
        if "artifact" in prompt or "mis-assembly" in prompt:
            return json.dumps(
                {
                    "stance": "undecided",
                    "confidence": 0.4,
                    "argument": (
                        "A period CV near zero is consistent with a real array and "
                        "equally with a collapsed assembly. Read depth would "
                        "separate them and is not available here."
                    ),
                    "what_would_settle_it": "per-base read depth across the array",
                }
            )
        if "already-described" in prompt or "already described" in prompt:
            return json.dumps(
                {
                    "stance": "undecided",
                    "confidence": 0.3,
                    "argument": (
                        "No covariance-model scan was run, so an existing family "
                        "cannot be excluded. Absence of a match was never tested."
                    ),
                    "what_would_settle_it": "an Infernal scan against Rfam",
                }
            )
        return json.dumps(
            {
                "stance": "survives",
                "confidence": 0.5,
                "argument": (
                    "Nine copies at a near-constant period is not what random "
                    "sequence of this composition produces."
                ),
                "what_would_settle_it": "the same architecture in unrelated genomes",
            }
        )


def main() -> None:
    sequence = synthesise()
    state = CandidateState(
        candidate_id="demo_0001", sequence=sequence, contig_id="synthetic_contig"
    )

    loop = InvestigationLoop(
        registry=registry, investigator=ScriptedInvestigator(script(sequence))
    )
    result = loop.run(state)

    print("Investigation")
    print("-" * 66)
    print(f"iterations      : {result.iterations}")
    print(f"tools run       : {result.requests_made}")
    print(f"requests refused: {result.requests_refused}")
    print(f"budget spent    : {state.spent}")
    print(f"stopped because : {result.stop.code} — {result.stop.detail}")
    print()

    review = AdversarialReview(client=CautiousAdversary()).run(state)
    print("Adversarial review")
    print("-" * 66)
    for challenge in review.challenges:
        print(
            f"  {challenge.name:20s} {challenge.stance:10s} "
            f"({challenge.confidence:.2f})"
        )
    print(f"  => {'survived' if review.survived else 'eliminated'}")
    print()

    out = Path("discovery_runs/demo_0001")
    state.save(out / "state.json")
    report_path = DiscoveryReport(state, review).save(out / "report.md")
    print(f"State  : {out / 'state.json'}")
    print(f"Report : {report_path}")
    print()
    print("Unresolved after review:")
    if review.unresolved:
        for name in review.unresolved:
            print(f"  - {name}")
    else:
        print("  (none recorded)")
    print()
    print(
        "The data above is synthetic and generated by this file. It demonstrates "
        "the mechanism and the record, not a discovery."
    )


if __name__ == "__main__":
    main()
