"""A runnable end-to-end demonstration on synthetic data.

    python -m discovery.demo

This is a **mechanism demo, not a result**. The loci are generated by this file,
so the fact that the engine finds the planted array proves only that the wiring
works. It exists to make the shape of the funnel concrete and to give the tests
something honest to assert against.

Note where the model sits: three deterministic stages run first and cut the pool
down, and only then does the agent layer see anything.
"""

from __future__ import annotations

import random

from discovery.agents.base import RuleBasedClient
from discovery.agents.review import AdversarialReview
from discovery.features.neighborhood import (
    Gene,
    Neighbourhood,
    cross_genome_support,
    neighbourhood_features,
)
from discovery.features.repeats import repeat_features
from discovery.features.sequence import sequence_features
from discovery.schema import Candidate
from discovery.scoring import NoveltyScorer
from discovery.stages import Cost, Pipeline, Stage, escalation_rule, threshold_rule

KNOWN_ARCHITECTURES = {("RT", "capsid"), ("RT", "integrase", "capsid"), ("transposase",)}
KNOWN_FAMILIES = {"RT", "capsid", "integrase", "transposase", "helicase"}
ARRAY_UNIT = "CATGTGTATCGCATGTTACGTACGT"


def _dna(n: int, rng: random.Random) -> str:
    return "".join(rng.choice("ACGT") for _ in range(n))


def synthesise(seed: int = 0) -> tuple[list[Candidate], list[Neighbourhood]]:
    """Build a small mixed pool: junk, known systems, and one planted array."""
    rng = random.Random(seed)
    candidates: list[Candidate] = []
    neighbourhoods: list[Neighbourhood] = []

    def add(cid: str, sequence: str, families: list[str], taxon: str) -> None:
        genes = [
            Gene(gene_id=f"{cid}_g{i}", family=family, start=i * 900, end=i * 900 + 700)
            for i, family in enumerate(families)
        ]
        neighbourhood = Neighbourhood(
            contig_id=cid, anchor_family="RT", genes=genes, taxon=taxon
        )
        neighbourhoods.append(neighbourhood)
        candidates.append(
            Candidate(
                candidate_id=cid,
                sequence=sequence,
                contig_id=cid,
                start=0,
                end=len(sequence),
            )
        )

    # 1. Low-complexity junk -- should die at QC.
    for i in range(4):
        add(f"junk_{i}", "AT" * 1500, ["RT", "orfZ"], f"tax_{i}")

    # 2. Known systems -- real, but already described.
    for i in range(6):
        add(f"known_{i}", _dna(4000, rng), ["RT", "capsid"], f"tax_k{i}")

    # 3. Unusual partner, no repeat structure -- interesting, not compelling.
    for i in range(3):
        add(f"partner_{i}", _dna(4000, rng), ["RT", "orfX"], f"tax_p{i}")

    # 4. The planted signal: an unusual partner AND a regular repeat array,
    #    seen in several unrelated taxa.
    for i in range(4):
        sequence = _dna(400, rng)
        for _ in range(9):
            sequence += ARRAY_UNIT + _dna(140 - len(ARRAY_UNIT), rng)
        sequence += _dna(400, rng)
        add(f"array_{i}", sequence, ["RT", "orfX", "orfY"], f"tax_a{i}")

    return candidates, neighbourhoods


def annotate(candidates: list[Candidate], neighbourhoods: list[Neighbourhood]) -> None:
    """Attach every deterministic feature block. No model involved."""
    support = cross_genome_support(neighbourhoods)
    for candidate, neighbourhood in zip(candidates, neighbourhoods, strict=True):
        candidate.features.update(sequence_features(candidate.sequence))
        candidate.features.update(repeat_features(candidate.sequence))
        candidate.features.update(
            neighbourhood_features(
                neighbourhood, KNOWN_ARCHITECTURES, KNOWN_FAMILIES, support=support
            )
        )
        candidate.add_evidence(
            "architecture",
            "|".join(neighbourhood.architecture()),
            source="discovery.features.neighborhood",
        )


def build_pipeline(scorer: NoveltyScorer) -> Pipeline:
    def score_stage(candidate: Candidate):
        from discovery.stages import StageResult

        scores = scorer.score(candidate)
        return StageResult("keep", f"priority={scores['priority']:.3f}")

    return Pipeline(
        [
            Stage(
                "qc_complexity",
                Cost.TRIVIAL,
                threshold_rule("low_complexity_fraction", maximum=0.30),
                "Drop low-complexity sequence, which mimics novelty.",
            ),
            Stage(
                "known_systems",
                Cost.CHEAP,
                threshold_rule("architecture_novelty", minimum=0.25),
                "Set aside architectures that match a described system.",
            ),
            Stage(
                "independent_support",
                Cost.CHEAP,
                threshold_rule("cross_genome_support", minimum=2),
                "Require the arrangement in more than one taxon.",
            ),
            Stage("score", Cost.MODERATE, score_stage, "Compute novelty and priority."),
            Stage(
                "escalate",
                Cost.MODERATE,
                escalation_rule("priority", minimum=0.20),
                "Only escalated candidates reach the model.",
            ),
        ]
    )


def main() -> None:
    candidates, neighbourhoods = synthesise()
    annotate(candidates, neighbourhoods)

    run = build_pipeline(NoveltyScorer()).run(candidates)

    print("Deterministic funnel")
    print("-" * 60)
    print(run.funnel())
    print()

    escalated = sorted(
        run.survivors, key=lambda c: c.scores.get("priority", 0.0), reverse=True
    )
    print(f"Reached the agent layer: {len(escalated)} of {len(candidates)}")
    print("-" * 60)

    review = AdversarialReview(client=RuleBasedClient(threshold=0.25))
    survivors = []
    for candidate in escalated:
        outcome = review.run(candidate)
        print(outcome.summary().splitlines()[0])
        if outcome.survived:
            survivors.append(candidate)

    print()
    print(f"Survived adversarial review: {len(survivors)}")
    for candidate in survivors:
        print(
            f"  {candidate.candidate_id}: "
            f"priority={candidate.scores['priority']:.3f} "
            f"copies={candidate.features['repeat_copy_count']:.0f} "
            f"period={candidate.features['repeat_mean_period']:.0f}bp"
        )
    print()
    print(
        "Reminder: the data above is synthetic and generated by this file. "
        "This demonstrates the mechanism, not a discovery."
    )


if __name__ == "__main__":
    main()
